# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  HUSKY: 0

jobs:
  publish-binary:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            publish: win-x64
          - os: ubuntu-latest
            publish: linux-x64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Publish GitRepo
        run: dotnet publish -c Release src/GitRepo/GitRepo.csproj --runtime ${{ matrix.publish }} -o ./publish/${{ matrix.publish }} -p:PublishAot=true
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.publish }}
          path: ./publish/${{ matrix.publish }}
          retention-days: 7

  publish-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Create NuGet package
        run: dotnet pack -c Release -o ./artifacts
      - name: Publish NuGet package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget
          path: ./artifacts
          retention-days: 7
