# When publishing a release from a tag, build the project and publish the packages to nuget.
# Package version should correspond to the tag. If tag is v1.0.1, nuget package should have 1.0.1 as a version.
# Nuget key will be fetched from Akeyless using appropriate action.

name: Publish to NuGet

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Fetch static secrets from Akeyless
        uses: akeyless-community/akeyless-github-action@v1.0.1
        id: fetch-secrets
        with:
          access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
          access-key: ${{ secrets.AKEYLESS_ACCESS_KEY }}
          access-type: access_key
          static-secrets: |
            - name: "/keys/nuget"
              output-name: "NUGET_API_KEY"
      - name: Create NuGet package
        # need to remove 'v' from the tag
        run: dotnet pack -c Release -o ./artifacts -p:Version=${GITHUB_REF#refs/tags/v}
      - name: Publish NuGet package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ./artifacts
